# Generated by Django 4.2.29 on 2026-03-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_archivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
